[package]
name = "glowrs-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glowrs = { path = "../glowrs" }
candle-core = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
axum = { version = "0.7.4", features = ["macros"] }
bytes = "1.5.0"
console-subscriber = "0.2.0"
futures-util = "0.3.28"
serde = { version = "1.0.183", features = ["derive"] }
tokio = { version = "1.31.0", features = ["full", "rt-multi-thread", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.18"
uuid = { version = "1.6.1", features = ["v4"] }
serde_json = "1.0.111"
tokenizers = "0.15.0"
hf-hub = { version = "0.3.2", features = ["tokio"] }
anyhow = "1.0.79"
thiserror = "1.0.56"
tracing-chrome = "0.7.1"
tower-http = { version = "0.5.1", features = ["trace", "timeout"] }
once_cell = "1.19.0"
clap = { version = "4.4.18", features = ["derive"] }


[features]
default = []
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]