name: Build & Register Image
on:
  push:
    branches:
      - master

jobs:
  build-and-register:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Check current version
        id: check-version
        run: |
          echo "LOCAL_VERSION=$(grep -e '^version\s*=\s*"' Cargo.toml | head -1 | cut -d '"' -f2)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/wdoppenberg/glowrs-server:${{ env.LOCAL_VERSION }}-cpu
            ghcr.io/wdoppenberg/glowrs-server:latest

