name: Publish Package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            crates/glowrs
            crates/glowrs-server

      - name: Publish glowrs
        run: (cd crates/glowrs && cargo publish --token ${{ secrets.CRATES_TOKEN }})