name: Publish Package
on:
  release:
    types: [ published ]
    
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Check current version
        id: check-version
        run: |
          LAST_PUBLISHED_VERSION=$(cargo search glowrs --limit 1 | awk '{print $3}' | tr -d '"')
          LOCAL_VERSION=$(grep -e '^version\s*=\s*"' Cargo.toml | head -1 | cut -d '"' -f2)
          if [ "$LAST_PUBLISHED_VERSION" == "$LOCAL_VERSION" ]; then
            exit 1 # Force a failure if the versions match
          fi

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            crates/glowrs
            crates/glowrs-server

      - name: Publish glowrs
        run: cargo publish -p glowrs --token ${{ secrets.CRATES_TOKEN }}
