name: Build & Test

on:
  push:
    branches: [ "master" ]
    paths:
      - "crates/**"
      - ".github/workflows/rust.yml"
      - "tests/**"
      - "Cargo.toml"
      - ".cargo/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "crates/**"
      - ".github/workflows/rust.yml"
      - "tests/**"
      - "Cargo.toml"
      - ".cargo/**"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test multiple workspaces on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          crates/glowrs
          crates/glowrs-server

    - name: Build
      run: cargo build --verbose

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Check clippy
      run: cargo clippy -- -D warnings

    - name: Publish dry-run
      run: cargo publish -p glowrs --dry-run

    - name: Run tests
      run: cargo test --verbose
