name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          crates/glowrs
          crates/glowrs-server

    - name: Build
      run: cargo build --verbose

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Check clippy
      run: cargo clippy -- -D warnings

    - name: Publish dry-run
      run: (cd crates/glowrs && cargo publish --dry-run)

    - name: Run tests
      run: cargo test --verbose
